<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DaftarTilikSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Hapus data lama jika diperlukan (hati-hati jika ini data penting)
        // DB::table('tilik')->delete();

        DB::table('tilik')->insert([
            [
                'kriteria_id' => 1, 
                'pertanyaan' => 'Apakah  visi yang mencerminkan visi perguruan tinggi dan memayungi visi keilmuan terkait keunikan program studi serta didukung data implementasi yang konsisten?',
                'indikator' => 'LAM Emba, LAM Infokom, LAM Teknik',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 1,
                'pertanyaan' => 'Apakah misi, tujuan, dan strategi yang searah dan strategi perguruan tinggi serta mendukung pengembangan program studi dengan data implementasi yang konsisten?',
                'indikator' => 'LAM Emba, LAM Infokom, LAM Teknik',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 1,
                'pertanyaan' => 'Apakah Strategi efektif untuk mencapai tujuan dan disusun berdasarkan analisis yang sistematis dengan menggunakan metode yang relevan dan terdokumentasi serta pada pelaksanaannya dilakukan pemantauan dan evaluasi dan ditindaklanjuti?',
                'indikator' => 'LAM Emba, LAM Infokom, LAM Teknik',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '1. Apakah sudah ada  struktur organisasi yg jelas untuk UPPS ?',
                'indikator' => 'Unit Pengelola Program Studi mendeskripsikan proses, struktur dan tradisi dalam menjalankan tugas dan menggunakan wewenangnya untuk mengemban misi, mewujudkan visi dan mencapai tujuan serta sasaran strategisnya yang didukung perilaku etis dan berintegritas para pengelola, tenaga kependidikan, mahasiswa dan mitra Unit Pengelola Program Studi.',
                'sumber_data' => 'Statuta dan SOTK, SK UPPS dan Tupoksi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '2. Apakah sudah ada tupoksi yang jelas dari Unit Pengelola Program Studi?',
                'indikator' => 'Unit Pengelola Program Studi mendeskripsikan proses, struktur dan tradisi dalam menjalankan tugas dan menggunakan wewenangnya untuk mengemban misi, mewujudkan visi dan mencapai tujuan serta sasaran strategisnya yang didukung perilaku etis dan berintegritas para pengelola, tenaga kependidikan, mahasiswa dan mitra Unit Pengelola Program Studi.',
                'sumber_data' => 'Statuta dan SOTK, SK UPPS dan Tupoksi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '3. Apakah sudah ada pedoman ataupun kode etik bagi UPPS ?',
                'indikator' => 'Unit Pengelola Program Studi mendeskripsikan proses, struktur dan tradisi dalam menjalankan tugas dan menggunakan wewenangnya untuk mengemban misi, mewujudkan visi dan mencapai tujuan serta sasaran strategisnya yang didukung perilaku etis dan berintegritas para pengelola, tenaga kependidikan, mahasiswa dan mitra Unit Pengelola Program Studi.',
                'sumber_data' => 'Statuta dan SOTK, SK UPPS dan Tupoksi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '1. Apakah sudah  ada pedoman jelas pembuatan laporan kinerja UPPS?',
                'indikator' => 'Unit Pengelola Program Studi mendeskripsikan peran, tanggung jawab, wewenang dan proses pengambilan keputusan untuk pencapaian efektivitas organisasi berdasarkan visi, misi, tujuan dan strategi serta  menggunakan lima pilar sistem tata pamong, yang mencakup:  kredibel, transparan, akuntabel, bertanggung jawab dan adil.',
                'sumber_data' => 'Lakin UPPS',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '2. Apakah kinerja UPPS memenuhi kriteria 5 pilar sistim tata pamong?',
                'indikator' => 'Unit Pengelola Program Studi mendeskripsikan peran, tanggung jawab, wewenang dan proses pengambilan keputusan untuk pencapaian efektivitas organisasi berdasarkan visi, misi, tujuan dan strategi serta  menggunakan lima pilar sistem tata pamong, yang mencakup:  kredibel, transparan, akuntabel, bertanggung jawab dan adil.',
                'sumber_data' => 'Lakin UPPS',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '1. Bagaimanakah program kerja UPPS?',
                'indikator' => 'Unit Pengelola Program Studi mendeskripsikan perencanaan, pengorganisasian, pengarahan dan pengendalian sumber daya agar program studi dapat menjalankan tugas dan kewajibannya secara efektif dan efisien serta akuntabel, bertanggung jawab, transparan, adil dan terhindar dari konflik kepentingan yang ditunjukkan dengan hasil evaluasi kepuasan para pemangku kepentingan terhadap keterlaksanaan dan efektivitas  tata kelola.',
                'sumber_data' => 'Renop UPPS',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '2. Apakah Unit Pengelola Program Studi secara periodik melakukan survey kepuasan pelanggan?',
                'indikator' => 'Unit Pengelola Program Studi mendeskripsikan perencanaan, pengorganisasian, pengarahan dan pengendalian sumber daya agar program studi dapat menjalankan tugas dan kewajibannya secara efektif dan efisien serta akuntabel, bertanggung jawab, transparan, adil dan terhindar dari konflik kepentingan yang ditunjukkan dengan hasil evaluasi kepuasan para pemangku kepentingan terhadap keterlaksanaan dan efektivitas  tata kelola.',
                'sumber_data' => 'Renop UPPS',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '3. Apakah ada tindak lanjut dari hasil survey kepuasan pelanggan?',
                'indikator' => 'Unit Pengelola Program Studi mendeskripsikan perencanaan, pengorganisasian, pengarahan dan pengendalian sumber daya agar program studi dapat menjalankan tugas dan kewajibannya secara efektif dan efisien serta akuntabel, bertanggung jawab, transparan, adil dan terhindar dari konflik kepentingan yang ditunjukkan dengan hasil evaluasi kepuasan para pemangku kepentingan terhadap keterlaksanaan dan efektivitas  tata kelola.',
                'sumber_data' => 'Renop UPPS',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '1. Apakah UPPS telah menerapkan   siklus SPMI ?',
                'indikator' => 'Unit Pengelola Program Studi mendeskripsikan sistem manajemen mutu internal yang diimplementasikan secara konsisten, efektif dan efisien serta dilaporkan secara berkala untuk tindak lanjut peningkatan mutu pendidikan tinggi.',
                'sumber_data' => 'Dokumen SPMI, Notulen RTM, Peringkat akreditasi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '1. Apa saja jenis dan bentuk kerjasama UPPS dengan mitra ?',
                'indikator' => 'Unit Pengelola Program Studi menjelaskan kegiatan dengan para mitranya dan hasil dari kegiatan tersebut.',
                'sumber_data' => 'Mou & MoA, Lakin UPPS',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            #asas
            [
                'kriteria_id' => 2,
                'pertanyaan' => '2.  Adakah Laporan hasil kerjasama dengan mitra ?',
                'indikator' => 'Unit Pengelola Program Studi menjelaskan kegiatan dengan para mitranya dan hasil dari kegiatan tersebut.',
                'sumber_data' => 'Mou & MoA, Lakin UPPS',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '3.  Apakah mitra kerjasama memiliki akses terhadap laporan tsb. ?',
                'indikator' => 'Unit Pengelola Program Studi menjelaskan kegiatan dengan para mitranya dan hasil dari kegiatan tersebut.',
                'sumber_data' => 'Mou & MoA, Lakin UPPS',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '1. Apakah semua kerjasama mendukung tercapanya VMTS UPPS ?',
                'indikator' => 'Unit Pengelola Program Studi menjelaskan keselarasan dan konsistensi antara kerja sama, visi, misi, tujuan dan aspirasi para pemangku kepentingan dengan memperhatikan isu ekonomi dan bisnis yang berkembang untuk memberi dampak positif kepada para pemangku kepentingan dan masyarakat luas.',
                'sumber_data' => 'Lakin UPPS',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => ' 2. Adakah kerjasama  yang tidak sesuai VMTS ? Mengapa ?',
                'indikator' => 'Unit Pengelola Program Studi menjelaskan keselarasan dan konsistensi antara kerja sama, visi, misi, tujuan dan aspirasi para pemangku kepentingan dengan memperhatikan isu ekonomi dan bisnis yang berkembang untuk memberi dampak positif kepada para pemangku kepentingan dan masyarakat luas.',
                'sumber_data' => 'Lakin UPPS',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '1. Apasaja kerjasama UPPS dengan para stake holder di bidang tridharma ? ',
                'indikator' => 'Unit Pengelola Program Studi menjelaskan cakupan kerja sama bidang Ilmu EMBA dan dampaknya. Kegiatan kerja sama program studi dapat mencakup bidang pendidikan, penelitian, dan/atau pengabdian kepada masyarakat dengan memperhatikan isu ekonomi dan bisnis yang berkembang di tingkat lokal, nasional, dan/atau internasional.',
                'sumber_data' => 'Lakin UPPS',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '2. Apakah aset yang diperoleh dari kerjasama dengan maitra ?',
                'indikator' => 'Unit Pengelola Program Studi menjelaskan cakupan kerja sama bidang Ilmu EMBA dan dampaknya. Kegiatan kerja sama program studi dapat mencakup bidang pendidikan, penelitian, dan/atau pengabdian kepada masyarakat dengan memperhatikan isu ekonomi dan bisnis yang berkembang di tingkat lokal, nasional, dan/atau internasional.',
                'sumber_data' => 'Lakin UPPS',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 2,
                'pertanyaan' => '1. Bagaimanakah keberlanjutan kerjasama dengan mitra / stake holder ?',
                'indikator' => 'Unit Pengelola Program Studi melakukan evaluasi kerjasama secara berkala dan tindak lanjut dengan mempertimbangkan dampak internal dan eksternal kerjasama.',
                'sumber_data' => 'Lakin UPPS',
                'metode_perhitungan' => null,
                'target' => null,
            ],


            [
                'kriteria_id' => 4,
                'pertanyaan' => 'Berapakah persentase perolehan dana yang bersumber dari mahasiswa?',
                'indikator' => 'IKT.3.02.01',
                'sumber_data' => 'Data Dana  dari mahasiswa (SPP),	Daftar perolehan/ sumber dana PT',
                'metode_perhitungan' => 'Persentase perolehan dana yang bersumber dari mahasiswa D3 terhadap total perolehan dana perguruan tinggi.',
                'target' => null,
            ],
            [
                'kriteria_id' => 4,
                'pertanyaan' => 'Berapa prosentase program, kegiataan dan penganggaran berbasis kinerja?',
                'indikator' => 'IKT.3.02.02',
                'sumber_data' => 'Sirena,	Program kegiatan yang terdanai',
                'metode_perhitungan' => 'Persentase Usulan kegiatan yang terdanai dengan jumlah usulan kegiatan',
                'target' => null,
            ],
            [
                'kriteria_id' => 4,
                'pertanyaan' => 'Berapa nilai rata-rata Kinerja anggaran atas Pelaksanaan RKA-K/L Satker minimal 93',
                'indikator' => 'IKT.3.02.03',
                'sumber_data' => 'SPI',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 4,
                'pertanyaan' => 'Berapa indeks opini Audit Laporan keuangan',
                'indikator' => 'IKT.3.02.05',
                'sumber_data' => 'SPI',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 4,
                'pertanyaan' => 'Berapa indeks kepuasan layanan akademik dan non akademik?',
                'indikator' => 'IKT.3.03.02',
                'sumber_data' => 'Hasil kuesioner mahasiswa',
                'metode_perhitungan' => 'Rata-rata nilai dari setiap indikator kuesioner',
                'target' => null,
            ],
            [
                'kriteria_id' => 4,
                'pertanyaan' => 'Berapa jumlah layanan akademik dan non akademik berbasis teknologi informasi yang terintegrasi?',
                'indikator' => 'IKT.3.03.03',
                'sumber_data' => 'Sistem Informasi yang ada di Polines',
                'metode_perhitungan' => 'Jumlah aplikasi sistem informasi yang digunakan di Polines, Jurusan, Prodi',
                'target' => null,
            ],
            [
                'kriteria_id' => 4,
                'pertanyaan' => 'Berapa kapasitas total bandwidth internet?',
                'indikator' => 'IKT.3.03.04',
                'sumber_data' => 'PTIK',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 4,
                'pertanyaan' => 'Adakah perpustakaan Digital?',
                'indikator' => 'IKU.3.04.01',
                'sumber_data' => 'Perpustakaan',
                'metode_perhitungan' => 'Ketersediaan Buku, jurnal dan sumber pustaka digital dibanding total sumber pustaka di perpustakaan ',
                'target' => null,
            ],
            [
                'kriteria_id' => 4,
                'pertanyaan' => 'Berapa jumlah peralatan laboratorium yang relevan dengan industri, atau mendukung teaching industry yang berkolaborasi dengan industri dan dunia kerja?',
                'indikator' => 'IKU.3.04.01',
                'sumber_data' => 'Peralatan yang terdapat di laboratorium',
                'metode_perhitungan' => 'Jumlah peralatan yang terdapat di laboratorium',
                'target' => null,
            ],
// mulai sini
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen pemenuhan Dosen dengan kualifikasi minimal S2 yang mengajar S1 dan Diploma?',
                'indikator' => 'SPM 5.1.1',
                'sumber_data' => 'Data pendidikan dosen',
                'metode_perhitungan' => 'Jumlah dosen S2 mengajar STr dan D3/ jumlah total dosen',
                'target' => '100%',
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen pemenuhan Dosen dengan kualifikasi minimal S3 yang mengajar S2?',
                'indikator' => 'SPM 5.1.2',
                'sumber_data' => 'Data pendidikan dosen',
                'metode_perhitungan' => 'Jumlah dosen S3 mengajar S2/jumlah total dosen',
                'target' => '100%',
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen dosen PS  yang memiliki kesesuaian bidang keilmuan dengan mata kuliah yang diampu?',
                'indikator' => 'SPM 5.1.3, IKU 4.01.07',
                'sumber_data' => 'Data mata kuliah yang diampu dosen, Data dosen dengan bid keilmuan',
                'metode_perhitungan' => ' Jumlah dosen mengampu mata kuliah sesuai bidang keilmuan/jumlah total dosen',
                'target' => '96,5%',
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapakah perbandingan jumlah dosen dan mahasiswa?',
                'indikator' => 'SPM 5.2.1, IKU 4.01.01, BAN C.4.4a',
                'sumber_data' => 'Data dosen, Data mahaiswa',
                'metode_perhitungan' => 'Rasio dosen terhadap mahasiswa',
                'target' => '1:14',
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen jumlah dosen tetap dari jumlah seluruh dosen?',
                'indikator' => 'SPM 5.2.2',
                'sumber_data' => 'Data dosen tetap, Data seluruh dosen',
                'metode_perhitungan' => ' Rasio dosen tetap /jumlah total dosen',
                'target' => '94%',
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen jumlah dosen yang mengikuti peningkatan kualifikasi pendidikan?',
                'indikator' => 'SPM 5.2.3.1',
                'sumber_data' => 'Data dosen  sedang studi lanjut',
                'metode_perhitungan' => 'Rasio dosen sedang studi lanjut/ jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen jumlah dosen yang mengikuti peningkatan kompetensi?',
                'indikator' => 'SPM 5.2.3.2',
                'sumber_data' => 'Data dosen mengikuti sertidikasi kompetensi',
                'metode_perhitungan' => ' Rasio dosen yg mengikuti peningkatan kompetensi/ jumlah total dosen',
                'target' => '20%',
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen jumlah dosen yang memiliki kesesuaian dengan kompetensi inti Program Studi?',
                'indikator' => 'IKU.4.01.02, BAN C.4.4.a',
                'sumber_data' => 'Data dosen  sesuai kompetensi inti PS, Data mata kuliah yang diampu dosen',
                'metode_perhitungan' => ' Jumlah dosen mengampu mata kuliah sesuai/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen dosen dengan jabatan lektor kepala?',
                'indikator' => 'IKU.4.01.03, BAN C.4.4.a',
                'sumber_data' => 'Daftar  lektor kepala',
                'metode_perhitungan' => 'Jumlah lektor kepala/jumlah total dosen',
                'target' => null, #9
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen dosen dengan jabatan guru besar?',
                'indikator' => 'IKU.4.01.04, BAN C.4.4.a',
                'sumber_data' => 'Daftar guru besar',
                'metode_perhitungan' => 'Jumlah guru besar/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen dosen bersertifikat pendidik profresional?',
                'indikator' => 'IKU.4.01.05',
                'sumber_data' => 'Daftar dosen bersertifikat pendidik profresional',
                'metode_perhitungan' => 'Jumlah dosen bersertifikat pendidik profresional/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen jumlah dosen bersertifikat kompetensi/profesi/industri?',
                'indikator' => 'IKU.4.01.06, BAN C.4.4.a',
                'sumber_data' => 'Daftar dosen bersertifikatkompetensi/profesi/industri',
                'metode_perhitungan' => 'Jumlah dosen bersertifikat kompetensi/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen jumlah dosen berpendidikan S3?',
                'indikator' => 'IKU.4.01.08, BAN C.4.4.a',
                'sumber_data' => 'Data Dosen  mengikuti sertifikasi kompetensi',
                'metode_perhitungan' => 'Rasio Dosen yg mengikuti peningkatan kompetensi/jumlah total dosen',
                'target' => null, #13
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen jumlah dosen sebagai anggota organisasi profesi?',
                'indikator' => 'IKU.4.01.09',
                'sumber_data' => 'Data dosen sebagai anggota organisasi profesi',
                'metode_perhitungan' => ' Rasio Dosen sebagai anggota organisasi profesi/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen jumlah  SKS dosen mengajar penuh dalam Program Studi?',
                'indikator' => 'IKU.4.01.10',
                'sumber_data' => '·  Data SKS mata kuliah yang diampu dosen',
                'metode_perhitungan' => ' Rasio jumlah SKS dosen mengajar penuh/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen jumlah dosen tidak tetap?',
                'indikator' => 'IKU.4.01.11, BAN C.4.4.a',
                'sumber_data' => '·  Data dosen  tidak tetap',
                'metode_perhitungan' => ' Rasio dosen tidak tetap/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen jumlah dosen pembimbing tugas akhir?',
                'indikator' => 'IKU.4.01.12',
                'sumber_data' => '·  Data dosen pembimbing tugas akhir',
                'metode_perhitungan' => ' Rasio dosen pembimbing tugas akhir/jumlah total dosen',
                'target' => null, #17
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah pengakuan atau rekognisi dosen dalam negeri?',
                'indikator' => 'IKU.4.01.13, BAN C.4.4.b (kinerja dosen)',
                'sumber_data' => 'Data dosen yang mendapat rekognisi dalam negeri',
                'metode_perhitungan' => 'Jumlah total rekognisi dosen dalam negeri',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah pengakuan atau rekognisi dosen luar negeri?',
                'indikator' => 'IKU.4.01.14, BAN C.4.4.b',
                'sumber_data' => 'Data dosen yang mendapat rekognisi luar negeri',
                'metode_perhitungan' => 'Jumlah total rekognisi dosen luar negeri',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah dosen asing?',
                'indikator' => 'IKU.4.01.15',
                'sumber_data' => 'data dosen asing',
                'metode_perhitungan' => 'jumlah dosen asing',
                'target' => null, #20
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah dosen politeknik yang berasal dari industri (Dosen Praktisi)?',
                'indikator' => 'IKU.4.01.16, BAN C.4.4.a',
                'sumber_data' => 'Data dosen praktisi',
                'metode_perhitungan' => 'Jumlah dosen praktisi',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah dosen tamu dari industri rutin mengajar di kampus?',
                'indikator' => 'IKU.4.01.17',
                'sumber_data' => 'Data dosen tamu',
                'metode_perhitungan' => 'Jumlah dosen tamu dari industri',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen dosen yang berkegiatan tridharma di kampus lain, diQS100 berdasarkan bidang ilmu (QS100 by subject), bekerja sebagai praktisi di dunia industri, atau membina mahasiswa?',
                'indikator' => 'IKU.4.01.18, PK DIR 22 IKU 2.1',
                'sumber_data' => '. Data kegiatan dosen di kampus lain',
                'metode_perhitungan' => 'Rasio kegiatan dosen di kampus lain/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen dosen tetap berkuaifikasi akademik S3; memiliki sertifikasi kompetensi/profesi yang diakui oleh industri dan dunia kerja; atau berasal dari kalangan praktisi professional, dunia industri, atau dunia kerja?',
                'indikator' => 'IKU.4.01.19, PK DIR 22 IKU 2.2',
                'sumber_data' => '·  Data kompetensi dosen  S3',
                'metode_perhitungan' => 'Rasio dosen S3 dan memiliki sertifikat kompetensi/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah dosen industri/praktisi dalam proses pembelajaran yang direkrut melalui kerjasama dengan industry/perusahaan yang relevan (D3,STr)?',
                'indikator' => 'BAN C.4.4.a',
                'sumber_data' => 'Data dosen industri yang kerjasama dengan institusi  ',
                'metode_perhitungan' => 'Jumlah  dosen industri yang kerjasama dengan institusi  ',
                'target' => null, #25
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => ' Bagaimana kualifikasi, keahlian, dan kemilikan sertifikat kompetensi dosen industri?',
                'indikator' => 'BAN C.4.4.a',
                'sumber_data' => '·  Data kompetensi dosen industri yang kerjasama dengan institusi',
                'metode_perhitungan' => 'Jumlah  dosen bersertifikat industri yang kerjasama dengan institusi',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa rata rata Ekuivalensi Waktu Mengajar Penuh (EWMP) DTPS pada kegiatan pendidikan (pembelajaran dan pembimbingan, penelitian, PkM, dan tugas tambahan dan/atau penunjang?',
                'indikator' => 'BAN C.4.4.a',
                'sumber_data' => 'rata rata Ekuivalensi Waktu Mengajar Penuh (EWMP) DTPS',
                'metode_perhitungan' => 'Perhitungan EWMP DTPS',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah keluaran penelitian & PkM yang berhasil mendapat rekognisi internasional atau diterapkan oleh masyarakat per jumlah dosen dalam 3 tahun terakhir?',
                'indikator' => 'PK DIR 22, IKU 2.3',
                'sumber_data' => '·  Data keluaran penelitian & PkM mendapat rekognisi internasional atau diterapkan masyarakat',
                'metode_perhitungan' => ' Rasio keluaran penelitian & PkM mendapat rekognisi internasional atau diterapkan masyarakat/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah penelitian per jumlah dosen DTPS dalam 3 tahun terakhir (Tabel 3.d.3 LKPS)?',
                'indikator' => 'BAN C.4.4.b (kinerja dosen)',
                'sumber_data' => '·  Data penelitian dosen',
                'metode_perhitungan' => ' Rasio jumlah penelitian dosen/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah pelaksanaan Pengabdian kepada Masyarakat per jumlah dosen DTPS dalam 3 tahun terakhir (Tabel 3.d.4 LKPS)?',
                'indikator' => 'BAN C.4.4.b (kinerja dosen)',
                'sumber_data' => 'Data pengabdian kepada masyarakat  dosen',
                'metode_perhitungan' => ' Rasio jumlah Pkm dosen/jumlah total dosen',
                'target' => null, #30
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah luaran Lainnya yang dihasilkan per jumlah dosen DTPS dalam 3 tahun terakhir (Tabel 3.d.6)?',
                'indikator' => 'BAN C.4.4.b (kinerja dosen)',
                'sumber_data' => '·  Data luaran lain dosen',
                'metode_perhitungan' => ' Rasio luaran lainnya dosen/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah penelitian per jumlah dosen DTPS dalam 3 tahun terakhir (Tabel 3.d.3 LKPS)?',
                'indikator' => 'BAN C.4.4.b (kinerja dosen)',
                'sumber_data' => '·  Data penelitian dosen',
                'metode_perhitungan' => ' Rasio jumlah penelitian dosen/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah karya ilmiah DTPS yang disitasi per jumlah dosen dalam 3 tahun terakhir (Tabel 3.d.7)?',
                'indikator' => 'BAN C.4.4.b (kinerja dosen)',
                'sumber_data' => '·  Data karya ilmiah dosen yang disitasi',
                'metode_perhitungan' => ' Rasio jumlah karya ilmiah dosen yang disitasi/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah Produk/Jasa DTPS yang diadopsi oleh Industri/Masyarakat per jumlah dosen (Tabel 3.d.8)?',
                'indikator' => 'BAN C.4.4.b (kinerja dosen)',
                'sumber_data' => 'Data Produk/Jasa DTPS yang diadopsi oleh Industri/Masyarakat',
                'metode_perhitungan' => 'Rasio Produk/Jasa DTPS yang diadopsi oleh Industri/Masyarakat/jumlah total dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah dosen yang berkegiatan tridarma di kampus lain (nasional)?',
                'indikator' => '"PK DIR 22, IKU 2.1',
                'sumber_data' => 'Data dosen yang berkegiatan tridarma di kampus lain (nasional)',
                'metode_perhitungan' => 'Jumlah dosen yang berkegiatan tridarma di kampus lain (nasional)',
                'target' => null,
            ], #35
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah dosen yang berkegiatan tridharma di kampus QS 100 berdasarkan bidang ilmu?',
                'indikator' => 'PK DIR 22, IKU 2.1',
                'sumber_data' => 'Data dosen yang berkegiatan tridharma di kampus QS 100',
                'metode_perhitungan' => 'Jumlah dosen yang berkegiatan di kampus QS 100 berdasarkan bidang ilmu',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah dosen yang bekerja sebagai praktisi di DUDI?',
                'indikator' => 'PK DIR 22, IKU 2.1',
                'sumber_data' => 'Data dosen yang bekerja sebagai praktisi di DUDI',
                'metode_perhitungan' => ' Jumlah dosen yang bekerja sebagai praktisi di DUDI',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa jumlah dosen yang membina mahasiswa dan berhasil meraih prestasi tingkat nasional dalam 5 tahun terakhir?',
                'indikator' => 'PK DIR 22, IKU 2.1',
                'sumber_data' => 'Data dosen yang membina mahasiswa dan berhasil meraih prestasi tingkat nasional dalam 5 tahun terakhir',
                'metode_perhitungan' => 'Jumlah dosen yang membina mahasiswa dan berhasil meraih prestasi tingkat nasional',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Jumlah dosen yang membina mahasiswa dan berhasil meraih prestasi tingkat internasional dalam 5 tahun terakhir?',
                'indikator' => 'PK DIR 22, IKU 2.1',
                'sumber_data' => '. Data dosen yang membina mahasiswa dan berhasil meraih prestasi tingkat internasional dalam 5 tahun terakhir',
                'metode_perhitungan' => 'Jumlah dosen yang membina mahasiswa dan berhasil meraih prestasi tingkat internasional',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Apakah PS memiliki Human resource planning?',
                'indikator' => 'EMBA indikator 3: rencana dan implementasi pengembangan',
                'sumber_data' => '. Dokumen Human resource planning',
                'metode_perhitungan' => 'Ada dokumen Human resource planning ',
                'target' => null,
            ], #40
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Apa saja upaya pengembangan dosen?',
                'indikator' => 'BAN C.4.4.c (pengembangan dosen)',
                'sumber_data' => ' Jenis upaya pengembangan dosen',
                'metode_perhitungan' => 'Pelaksanaan upaya pengembangan dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Apakah telah memiliki mekanisme dan prosedur dalam pengembangan karir akademik, keikutsertaan sertifikasi profesional dosen dalam bidang EMBA dan sesuai dengan visi, misi, tujuan dan strategi?',
                'indikator' => '"SPMI EMBA indikator 4 kebijakan pengembangan',
                'sumber_data' => 'Dokumen mekanisme dan prosedur dalam pengembangan karir akademik, keikutsertaan sertifikasi profesional',
                'metode_perhitungan' => 'Ada dokumen mekanisme dan prosedur',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Apakah setiap dosen telah memiliki rencana pengembangan karier akademik dan rencana keikutsertaan sertifikasi profesional?',
                'indikator' => 'EMBA indikator 5 Rencana pengembangan setiap dosen',
                'sumber_data' => 'Dokumen rencana keikutsertaan sertifikasi profesional setiap dosen',
                'metode_perhitungan' => 'Setiap dosen telah memiliki rencana pengembangan karier akademik dan rencana keikutsertaan sertifikasi profesional ',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Apakah telah memiliki mekanisme dan prosedur dalam melakukan evaluasi, promosi dan penghargaan dosen dan sudah dikomunikasikan kepada dosen dengan jelas dan sistematis untuk mendukung visi, misi, tujuan dan strategi?',
                'indikator' => '"SPMI EMBA indikator 6 evaluasi, pengendalian dan peningkatan',
                'sumber_data' => 'Dokumen prosedur dalam melakukan evaluasi, promosi dan penghargaan dosen',
                'metode_perhitungan' => 'Ada dokumen  mekanisme dan prosedur dalam melakukan evaluasi, promosi dan penghargaan dosen',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Apakah dilakukan evaluasi kepuasan dosen terhadap pengelolaan SDM??',
                'indikator' => 'BAN PT',
                'sumber_data' => '. Dokumen hasil evaluasi kepuasan dosen terhadap pengelolaan SDM',
                'metode_perhitungan' => 'Dilaksanakannya evaluasi kepuasan dosen terhadap pengelolaan SDM',
                'target' => null,
            ],#45
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen tenaga kependidikan yang memiliki kesesuaian kualifikasi pendidikan?',
                'indikator' => 'SPM 5.4.1',
                'sumber_data' => 'Data tendik yang sesuai kualifikasi pendidikan',
                'metode_perhitungan' => ' Rasio Tendik yg sesuai kualifikasi pendidikan / Jumlah total Tendik',
                'target' => '90%',
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen tenaga kependidikan yang memiliki kesesuaian kompetensi/bidang keahlian?',
                'indikator' => 'SPM 5.4.2',
                'sumber_data' => 'Data tendik yang sesuai kompetensi/bidang keahlian',
                'metode_perhitungan' => ' Rasio Tendik yg sesuai kompetensi/ jumlah total Tendik',
                'target' => '90%',
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Apakah tersedia sasaran kinerja pegawai?',
                'indikator' => 'SPM 5.4.3',
                'sumber_data' => 'Data SKP tendik',
                'metode_perhitungan' => 'Ada Data SKP tendik',
                'target' => 'Tersedia',
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapakah  perbandingan jumlah tenaga kependidikan (tertentu) dan mahasiswa?',
                'indikator' => 'SPM 5.4.4',
                'sumber_data' => 'Data tendik, Data Mahasiswa',
                'metode_perhitungan' => ' Rasio  JumlahTendik/ Jumlah Mahasiswa ',
                'target' => '1:57',
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen jumlah tenaga kependidikan yang mengikuti peningkatan kualifikasi pendidikan?',
                'indikator' => '"SPM 5.5.1',
                'sumber_data' => '·  Data tendik yang mengikuti peningkatan kualifikasi pendidikan',
                'metode_perhitungan' => ' Rasio Tendik yg studi lanjut/ jumlah total tendik',
                'target' => '35%',
            ], #50
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Berapa persen jumlah tenaga kependidikan yang mengikuti peningkatan kompetensi?',
                'indikator' => 'SPM 5.5.2, IKU 4.02.01',
                'sumber_data' => 'Data tendik yang mengikuti peningkatan kompetensi',
                'metode_perhitungan' => ' Rasio Tendik yg mengikuti peningkatan kompetensi/jumlah total tendik',
                'target' => '35%',
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Apakah memiliki Kualifikasi dan kecukupan tenaga kependidikan berdasarkan jenis pekerjaannya (administrasi, pustakawan, teknisi, dll.)?',
                'indikator' => 'BAN C.4.4.d (Tenaga Kependidikan)',
                'sumber_data' => 'Data tendik berdasar jenis pekerjaan',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Apakah memiliki kecukupan laboran untuk mendukung proses pembelajaran sesuai dengan kebutuhan prodi?',
                'indikator' => 'BAN C.4.4.d (Tenaga Kependidikan)',
                'sumber_data' => 'Data laboran',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Apakah UPPS telah memiliki mekanisme dan prosedur pengembangan karir akademik dan sertifikasi profesional bagi tenaga kependidikan sesuai dengan visi, misi, tujuan dan strategi?',
                'indikator' => '"EMBA SPMI',
                'sumber_data' => 'Dokumen prosedur pengembangan karir akademik dan sertifikasi profesional bagi tenaga kependidikan',
                'metode_perhitungan' => 'Dimilikinya prosedur pengembangan karir akademik dan sertifikasi profesional bagi tenaga kependidikan',
                'target' => null,
            ],
            [
                'kriteria_id' => 5,
                'pertanyaan' => 'Apakah dilakukan evaluasi kepuasan tenaga kependidikan terhadap pengelolaan SDM?',
                'indikator' => 'BAN PT',
                'sumber_data' => 'Dokumen hasil evaluasi kepuasan tenaga kependidikan terhadap pengelolaan SDM',
                'metode_perhitungan' => 'Dilakukan secara periodik evaluasi kepuasan tenaga kependidikan terhadap pengelolaan SDM',
                'target' => null,
            ],


            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah tersedia profil Lulusan, Capaian Pembelajaran Lulusan (CPL) sesuai dengan Profil Lulusan dan jenjang KKNI/SKKNI disertai bukti yang sahih dan sangat lengkap?',
                'indikator' => 'SPM 3.2.1',
                'sumber_data' => 'Dokumen Kurikulum',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah tersedia dokumen kurikulum yang lengkap dengan SK kurikulum?',
                'indikator' => 'SPM 3.2.1',
                'sumber_data' => 'Dokumen Kurikulum',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah RPS lengkap disusun dengan memuat 9 kompon inti sebagai berikut 1)Nama program studi, nama dan kode mata kuliah, semester, sks, nama dosen pengampu;2) Capaian Pembelajaran lulusan yang dibebankan pada mata kuliah;3) Kemampuan akhir yang direncanakan pada tiap tahap pembelajaran untuk memenuhi capaian pembelajaran lulusan;4) Bahan kajian yang terkait dengan kemampuan yang akan dicapai; 5) Metode pembelajaran;6) Waktu yang disediakan untuk mencapai kemampuan pada tiap tahap pembelajaran;7) Pengalaman belajar mahasiswa yang diwujudkan dalam deskripsi tugas yang harus dikerjakan oleh mahasiswa selama satu semester;8) Kriteria, indikator, dan bobot penilaian; dan 9) Daftar referensi yang digunakan?',
                'indikator' => 'SPM 3.2.1',
                'sumber_data' => 'Dokumen Kurikulum',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah tersedia kurikulum Program studi yang mutakhir dan relevan dengan kebutuhan ekonomi dan bisnis masadepa, memilii perpektif global, sesuai dengan VMTS dan Capaian pembelajaran ? (LamEMBA 6.a.1)',
                'indikator' => null,
                'sumber_data' => 'Dokumen Kurikulum',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah ada Monitoring dan Evaluasi kurikulum dan RPS serta selabus?',
                'indikator' => null,
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => null,
            ], #5
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah beban studi sesuai dengan SN Dikti?',
                'indikator' => 'SPM 3.2.2',
                'sumber_data' => 'Dokumen Kurikulum',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah ada kalender akademik?',
                'indikator' => 'SPM 3.2.3',
                'sumber_data' => 'Dokumen Kurikulum',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Berapakah frekwensi pembaharuan dan pengembangan kurikulum?',
                'indikator' => 'SPM 3.2.4',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah ada ketrlibatan pemangku kepentingan dalam proses  evaluasi dan Pemuthakiran Kurikulum?',
                'indikator' => 'SPM 3.3.4',
                'sumber_data' => 'Dokumen Evaluasi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah ada ketepatan waktu perkuliahan?',
                'indikator' => 'SPM 3.3.1',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ], #10
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah ada Jadwal tretulis?',
                'indikator' => 'SPM 3.3.1',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Berapakah prosentase Mahaseiswa hadir?',
                'indikator' => 'SPM 3.3.1',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah ada Punishment dan reward?',
                'indikator' => 'SPM 3.2.3',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Berapa prosentase kehadiran dosen pada Perkuliahan dan Praktikum?',
                'indikator' => 'SPM 3.3.4',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Berapa presentase mahasiswa menyesaikan tugas mandiri?',
                'indikator' => 'SPM 3.3.5',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],#15
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Berapa jumlah Matakuliah dan RPS yang dilengkapi dengan  Responsi/tutorial?',
                'indikator' => 'SPM 3.3.6',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah pelakssanaan ujian tepat waktu?',
                'indikator' => 'SPM 3.4.1',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah ada pedoman Tugas Akhir/Skripsi/tesis?',
                'indikator' => 'SPM 3.4.2',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah Prodi menyelenggarakan teaching industry?',
                'indikator' => 'IKU.1.02.11',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah  kurikulum yang disusun bersama industri (materi training dan sertifikasi di industri masuk resmi kedalam kurikulum di kampus)',
                'indikator' => 'IKU.3.03.06',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ], #20
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Jumlah penelitian/pengabdian yang terintegrasi ke dalam pengembangan kurikulum pembelajaran?',
                'indikator' => 'IKU.3.03.01',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah prodi menerapkan pembelajaran Problem Base Learning (PBL)?',
                'indikator' => 'Renstra New Cascading  1.3.2',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah prodi menerapkan pembelajaran Project Base Learning (PBL)?',
                'indikator' => 'Renstra New Cascading  1.3.2',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah ada pembelajaran  berbasis Digital/Blended Learning',
                'indikator' => 'Renstra New Cascading  1.3.7',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Berapakah jumlah mata kuliah yang menggunakan metode pembelajaran Project Base Learning (PBL)',
                'indikator' => 'Renstra New Cascading  1.3.8',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],#25
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah Program studi memiliki kebijakan implementasi "Merdeka Belajar Kampus Merdeka”?',
                'indikator' => 'Renstra KU.1.01.06 BANPT',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Adakah dokumen kerjasama UPPS dan Prodi dengan Perguruan Tinggi Mitra atau lembaga Mitra dalam pelaksanaan MBKM?',
                'indikator' => 'LAM infokom, EMBA, Teknik',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah ada bentuk interaksi dosen , mahasiswa dan sumber belajar?',
                'indikator' => 'LAM infokom, EMBA, Teknik',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah Program studi  melakukan evaluasi secara berkala mengenai kebijakan dan ketercapaian standar IKU dan IKT?',
                'indikator' => 'LAM infokom, EMBA, Teknik',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 6,
                'pertanyaan' => 'Apakah ada evaluasi kepuasan mahasiswa terhadap proses pembelajaran?',
                'indikator' => 'LAM infokom, EMBA, Teknik',
                'sumber_data' => 'Prodi',
                'metode_perhitungan' => null,
                'target' => null,
            ],

            
            [
                'kriteria_id' => 7,
                'pertanyaan' => 'Apakah UPPS memiliki peta jalan yang memayungi tema penelitian dosen?',
                'indikator' => 'IKU.2.01.01 Memiliki peta jalan yang memayungi tema penelitian dosen.',
                'sumber_data' => 'Dokumen peta jalan penelitian ',
                'metode_perhitungan' => 'Ketersediaan dokumen',
                'target' => null,
            ],
            [
                'kriteria_id' => 7,
                'pertanyaan' => 'Apakah dosen sudah melaksanakan penelitian sesuai dengan agenda penelitian dosen yang merujuk kepada peta jalan penelitian?',
                'indikator' => 'IKU.2.01.01 Dosen melaksanakan penelitian sesuai dengan agenda penelitian dosen yang merujuk kepada peta jalan penelitian.',
                'sumber_data' => 'Dokumen jumlah penelitian dosen sudah merujuk peta jalan penelitian',
                'metode_perhitungan' => 'Ketersediaan dokumen',
                'target' => null,
            ],
            [
                'kriteria_id' => 7,
                'pertanyaan' => 'Apakah UPPS sudah melakukan evaluasi kesesuaian penelitian dosen dengan peta jalan?',
                'indikator' => 'IKU.2.01.01Melakukan evaluasi kesesuaian penelitian dosen dengan peta jalan',
                'sumber_data' => 'Dokumen hasil evaluasi kesesuaian penelitian dosen dengan peta jalan penelitian',
                'metode_perhitungan' => 'Ketersediaan dokumen',
                'target' => null,
            ],
            [
                'kriteria_id' => 7,
                'pertanyaan' => 'Apakah UPPS dan PS sudah menggunakan hasil evaluasi untuk perbaikan relevansi penelitian dan pengembangan keilmuan program studi?',
                'indikator' => 'IKU.2.01.01Menggunakan hasil evaluasi untuk perbaikan relevansi penelitian dan pengembangan keilmuan program studi.',
                'sumber_data' => 'Dokumen hasil evaluasi untuk perbaikan relevansi penelitian ',
                'metode_perhitungan' => 'Ketersediaan dokumen',
                'target' => null,
            ],
            [
                'kriteria_id' => 7,
                'pertanyaan' => 'Berapa jumlah penelitian dosen yang dalam pelaksanaannya melibatkan mahasiswa program studi dalam 3 tahun terakhir?',
                'indikator' => 'IKU.2.03.01 Penelitian dosen yang dalam pelaksanaannya melibatkan mahasiswa program studi dalam 3 tahun terakhir',
                'sumber_data' => 'Jumlah dosen DTPS yang melaksanakan penelitian sudah melibatkan mahasiswa',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 7,
                'pertanyaan' => 'Apakah penelitian DTPS sudah melibatkan mahasiswa program studi setiap tahun minimal 50% dari jumlah judul penelitian untuk program Magister Terapan?',
                'indikator' => 'IKU.2.03.01 Penelitian DTPS wajib melibatkan mahasiswa program studi setiap tahun minimal 50% dari jumlah judul penelitian untuk program Magister Terapan',
                'sumber_data' => 'Dokumen penelitian DTPS minimal 50% judul penelitian sudah melibatkan mahasiswa prodi MST',
                'metode_perhitungan' => 'Ketersediaan dokumen',
                'target' => null,
            ],
            [
                'kriteria_id' => 7,
                'pertanyaan' => 'Berapakah jumlah penelitian dosen tetap program studi yang sudah menjadi rujukan tema tesis minimal 25% judul untuk program Magister?',
                'indikator' => 'IKU.2.03.02 Penelitian dosen tetap program studi wajib menjadi rujukan tema tesis minimal 25% judul untuk program Magister Terapan',
                'sumber_data' => 'Dokumen penelitian DTPS yang menjadi rujukan minimal 25% judul untuk prodi MST ',
                'metode_perhitungan' => 'Ketersediaan dokumen',
                'target' => null,
            ],


            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapakah Jumlah Judul Hasil PM berbasis aplikasi hasil penelitian?',
                'indikator' => 'Spm 17.1',
                'sumber_data' => 'Data dari P3M',
                'metode_perhitungan' => 'Disinkronkan dengan judul penelitian',
                'target' => null,
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa jumlah  judul  PM tiap tahun yang dapat digunakan untuk menyelesaikan masalah yang di hadapi masyarakat?',
                'indikator' => 'IKU.2.01.04',
                'sumber_data' => 'PM yang dimanfaatkan masyarakat dibuktikan dengan serah terima hasil PM dan VIdeo',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa jumlah judul  PM  tiaptahunnya sebagai bahan Pengembangan Iptek?',
                'indikator' => 'Spm 17.1',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa prosen Materi PM yang berdasarkan hasil Penelitian ?',
                'indikator' => 'Spm 18.1',
                'sumber_data' => '•	Kesesuaian   judul Penelitian Dengan PM',
                'metode_perhitungan' => 'Jumlah judul PM yang berdasar hasil Penelitian Dibanding Jumlah Judul PM keseluruhan',
                'target' => null,
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapakah Jumlah Judul Hasil PM berbasis aplikasi hasil penelitian?',
                'indikator' => 'Spm 17.1',
                'sumber_data' => '•	Dilihat pada Buku ajar atau pada buku nyang ditulis dosen yang mencantumkan referensi tentang judul PM',
                'metode_perhitungan' => null,
                'target' => null,
            ], #5
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa Presen Materi PM berdasarkan hasil Pengembangan IPTEK yang digunakan untuk Pemberdayaan Masyarakat?',
                'indikator' => 'Spm 18.1',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa Jumlah judul hasil PM yang berorientasi kepada kepentingan nasional?',
                'indikator' => 'Spm 18.1',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa kali dalam setahun diadakan Pelatihan Metodologi PM Penyusun- an Proposal, dan Penulisan Laporan?',
                'indikator' => 'Spm 19.1',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa Jumlah dosen yang mengikuti pelatihan?',
                'indikator' => 'Spm 19.1',
                'sumber_data' => 'Daftar Hadir',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa hari waktu yang dibutuhkan untuk seleksi proposal?',
                'indikator' => 'Spm 19.2',
                'sumber_data' => null,
                'metode_perhitungan' => 'Dihitung dari waktu terakhir mengumpulkan proposal sampai diummumkan proposal yang didanai',
                'target' => null,
            ], #10
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa jumlah proposal PM yang diseminarkan untuk pendanaan POLINES?',
                'indikator' => 'IKU.2.03.03',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa jumlah proposal PM yang diseminarkan untuk pendanaan nasional/ kementerian?',
                'indikator' => 'KU.2.01.05',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa jumlah kelompok masyarakat yang dilayani PM tiap tahunnnya?',
                'indikator' => 'Spm 19.3',
                'sumber_data' => 'Daftar kelompok masyarakkat penerima layanan Program PM',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa jumlah Mahasiswa yang terlibat dalam Kegiatan PM?',
                'indikator' => 'IKU.2.03.03',
                'sumber_data' => 'Daftar mhs Terlibat dalam Kegiatan ( ada pada proposal)',
                'metode_perhitungan' => null,
                'target' => null,
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa Jumlah Proposal PM yang dilaksanakan/ yang di danai?',
                'indikator' => 'Spm 19.3',
                'sumber_data' => null,
                'metode_perhitungan' => 'Daftar proposal yang diterima',
                'target' => null,
            ], # 15
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa minggu waktu yang diperlukan untuk penyampaian laporan hasil PM?',
                'indikator' => 'Spm 19.4',
                'sumber_data' => null,
                'metode_perhitungan' => 'Dihitung dari selesai pelaksanaan PM',
                'target' => null,
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Apakah ada Kriteria dan Prosedur yang Jelas untuk Penilaian terhadap Kegiatan PM?',
                'indikator' => 'IKU.2.03.04',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => 'ada',
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Apakah tersedia prosedur dan Akses bagi pemangku kepentingan terhadap kegiatan PM?',
                'indikator' => 'SPM 20.1',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => 'tersedia',
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa jumlah masyarakat mitra yang Memanfaatkan Hasil Kegiatan PM?',
                'indikator' => 'Spm 20.3',
                'sumber_data' => 'Daftar Mitra PM',
                'metode_perhitungan' => null,
                'target' => "59",
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Ada berapa jumlah Desa Binaan?',
                'indikator' => 'Spm 20.3',
                'sumber_data' => null,
                'metode_perhitungan' => 'Jumlah desa yang dibina oleh P3M dibuktikan dengan MOU',
                'target' => '7',
            ], #20
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa Prosentase Materi PM berdasarkan hasil Pengembangan IPTEK yang digunakan untuk Pemberdayaan Masyarakat?',
                'indikator' => 'Spm 20.3',
                'sumber_data' => null,
                'metode_perhitungan' => 'Jumlah judul materi pengembangan ITEK dibanding keseluruhan judul PM',
                'target' => '40',
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa ratio keterlibatan dosen dalam PM per tahun?',
                'indikator' => 'Spm 21.1',
                'sumber_data' => null,
                'metode_perhitungan' => 'Rasio dosen melakukan PM dibandingk-an total dosen',
                'target' => '7',
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'AApakah Materi PM oleh dosen sesuai dengan keahlian Dosen?',
                'indikator' => 'Spm 22.1',
                'sumber_data' => null,
                'metode_perhitungan' => 'Keahlian Dosen dihubungkan dengan materi PM yang diambil terutama ketua PM',
                'target' => 'sesuai',
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa besar rasio mahasiswa yang terlibat PM dosen dibandingkan total mahasiswa?',
                'indikator' => 'Spm 20.3',
                'sumber_data' => null,
                'metode_perhitungan' => 'Jumlah desa yang dibina oleh P3M dibuktikan dengan MOU',
                'target' => '1:7',
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Apakah tersedia fasilitas oleh Politeknik untuk melakukan PM terkait penerapan bidang ilmu dari program studi (Laboratorium, peralatan, dll)?',
                'indikator' => 'Spm 24.1',
                'sumber_data' => 'Daftar Inventaris',
                'metode_perhitungan' => null,
                'target' => 'Tersedia',
            ], #25
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Apakah tersedia fasilitas oleh Politeknik untuk melakukan PM terkait proses pembelajaran?',
                'indikator' => 'Spm 21.1',
                'sumber_data' => 'Daftar Inventaris',
                'metode_perhitungan' => null,
                'target' => 'Tersedia',
            ], 
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Apakah tersedia fasilitas oleh Politeknik untuk melakukan PM terkait penerapan bidang ilmu dari program studi (Laboratorium, peralatan, dll)?',
                'indikator' => 'Spm 22.1',
                'sumber_data' => 'Daftar Inventaris',
                'metode_perhitungan' => null,
                'target' => 'Tersedia',
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Apakah tersedia sistem informasi/ TIK untuk PM?',
                'indikator' => 'Spm 22.2',
                'sumber_data' => 'Bisa diakses',
                'metode_perhitungan' => null,
                'target' => 'Tersedia',
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Apakah Sarana dan Prasarana  memenuhi standar mutu, keselamatan kerja, kesehatan, kenyamanan, dan keamanan PM?',
                'indikator' => 'Spm 22.3',
                'sumber_data' => null,
                'metode_perhitungan' => 'Sesuaikan dengan standar',
                'target' => 'memenuhi',
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa persentase dana PM dibandingkan dengan total anggaran?',
                'indikator' => 'Spm 23.1',
                'sumber_data' => 'Daftar PO',
                'metode_perhitungan' => 'Dana PM dibanding Anggaran keseluruhan',
                'target' => '0.73',
            ], #30
            

            // Data dari gambar yang kamu unggah
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa Persen dana PM dari perguruan tinggi',
                'indikator' => 'SPM 23.1',
                'sumber_data' => 'Daftar PO',
                'metode_perhitungan' => null, // Tidak ada di gambar
                'target' => '28', // Bisa juga diinterpretasikan sebagai 28%
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa persentase dana PM dari pemerintah',
                'indikator' => 'SPM 23.1',
                'sumber_data' => 'Daftar PO',
                'metode_perhitungan' => null, // Tidak ada di gambar
                'target' => '45', // Bisa juga diinterpretasikan sebagai 45%
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Berapa persentase dana PM dari kerjasama lembaga lain',
                'indikator' => 'SPM 23.1',
                'sumber_data' => null, // Kolom ini kosong di gambar untuk baris ini
                'metode_perhitungan' => null, // Tidak ada di gambar
                'target' => '6',  // Bisa juga diinterpretasikan sebagai 6%
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Apakah tersedia mekanisme pembiayaan PM',
                'indikator' => 'SPM 24.1',
                'sumber_data' => 'Prosedur',
                'metode_perhitungan' => null, // Tidak ada di gambar
                'target' => 'tersedia',
            ],
            [
                'kriteria_id' => 8,
                'pertanyaan' => 'Apakah tersedia biaya pengelolaan PM untuk peningkatan kapasitas pelaksan PM', // Ada sedikit typo 'pelaksan' di gambar, saya asumsikan 'pelaksana'
                'indikator' => 'SPM 24.1',
                'sumber_data' => 'Daftar PO',
                'metode_perhitungan' => null, // Tidak ada di gambar
                'target' => 'tersedia',
            ],

            // Data dari gambar pertama (image_67c5d1.png)
            [
                'kriteria_id' => 9,
                'pertanyaan' => 'Berapakah IPK lulusan (Spm 1.5.1)',
                'indikator' => 'Spm 1.5.1',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => '3,3',
            ],
            [
                'kriteria_id' => 9,
                'pertanyaan' => 'Berapakah waktu tunggu lulusan yang mendapat pekerjaan (Spm.1.5.2)',
                'indikator' => 'Spm 1.5.2', // Normalisasi dari "Spm.1.5.2"
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => '0,3 Th',
            ],
            [
                'kriteria_id' => 9,
                'pertanyaan' => 'Berapakah jumlah hasil penelitian yang dipublikasikan pada jurnal yang terakreditasi',
                'indikator' => null, // Tidak ada kode SPM/IKU pada pertanyaan ini
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => '8 Penelitian',
            ],
            [
                'kriteria_id' => 9,
                'pertanyaan' => 'Berapakah jumlah hasil penelitian yang diaplikasikan',
                'indikator' => null, // Tidak ada kode SPM/IKU pada pertanyaan ini
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => '14 Judul/Th',
            ],
            [
                'kriteria_id' => 9,
                'pertanyaan' => 'Berapakah jumlah hasil penelitian yang tepat guna',
                'indikator' => null, // Tidak ada kode SPM/IKU pada pertanyaan ini
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => '14 Judul/Th',
            ],
            [
                'kriteria_id' => 9,
                'pertanyaan' => 'Berapakah jumlah HKI/Paten dan paten sederhana yang dihasilkan IKU.2.01.14 IKT.2.02.07',
                'indikator' => 'IKU.2.01.14 IKT.2.02.07',
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => '11 Judul/Th',
            ],

            // Data dari gambar kedua (image_67c30e.png)
            [
                'kriteria_id' => 9,
                'pertanyaan' => 'Berapakah jumlah hasil PM untuk Penyelesaian Masalah yang di hadapi Masyarakat',
                'indikator' => null, // Tidak ada kode SPM/IKU pada pertanyaan ini
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => '102 Judul PM/Th',
            ],
            [
                'kriteria_id' => 9,
                'pertanyaan' => 'Berapakah jumlah hasil PM sebagai bahan Pengembangan Iptek',
                'indikator' => null, // Tidak ada kode SPM/IKU pada pertanyaan ini
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => '56_Judul PM/Th', // Mengikuti format target dari gambar
            ],
            [
                'kriteria_id' => 9,
                'pertanyaan' => 'Berapakah jumlah hasil PM sebagai bahan pengayaan Bahan Ajar atau Modul Pelatihan',
                'indikator' => null, // Tidak ada kode SPM/IKU pada pertanyaan ini
                'sumber_data' => null,
                'metode_perhitungan' => null,
                'target' => '45_Judul PM/Th', // Mengikuti format target dari gambar
            ],
            
            

        ]);
    }
}
